name: Run Python Script from Another Repo

on: 
  push:
    branches:
      - main  # Runs when code is pushed to main
  workflow_dispatch:  # Allows manual execution

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Node.js Repository
        uses: actions/checkout@v3

      - name: Checkout Python Repository
        uses: actions/checkout@v3
        with:
          repository: alphyemmanuel/dependency-deprecator-analyzer  # Change this to your Python repo
          path: python-repo  # This will clone the Python repo into a folder

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Node.js Dependencies
        run: npm install  # Installs Node.js dependencies if package.json exists

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f python-repo/requirements.txt ]; then pip install -r python-repo/requirements.txt; fi

      - name: Run Python Script
        run: python python-repo/analyzer.py  # Running script from the cloned repo
