name: Run Python Script on Pull Request

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest
    env:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }} 
      HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}  
      REPO_OWNER: ${{ secrets.REPO_OWNER }}  
      
    steps:
      - name: Checkout Node.js Repository
        uses: actions/checkout@v3

      - name: Checkout Python Repository
        uses: actions/checkout@v3
        with:
          repository: alphyemmanuel/dependency-deprecator-analyzer  # Change this to your Python repo
          path: python-repo  # This will clone the Python repo into a folder

      - name: Check if Secrets Exist
        run: |
          if [ -z "$GIT_TOKEN" ]; then echo "❌ GIT_TOKEN is missing"; else echo "✅ GIT_TOKEN is set"; fi
          if [ -z "$HUGGINGFACE_TOKEN" ]; then echo "❌ HUGGINGFACE_TOKEN is missing"; else echo "✅ HUGGINGFACE_TOKEN is set"; fi
          if [ -z "$REPO_OWNER" ]; then echo "❌ REPO_OWNER is missing"; else echo "✅ REPO_OWNER is set"; fi
        shell: bash

      - name: Manually Set Test Secret
        run: |
         echo "GIT_TOKEN=test-secret" >> $GITHUB_ENV
         echo "HUGGINGFACE_TOKEN=test-secret" >> $GITHUB_ENV
         echo "REPO_OWNER=test-user" >> $GITHUB_ENV

      - name: Debug Test Secret
        run: |
         echo "GIT_TOKEN: $GIT_TOKEN"
         echo "HUGGINGFACE_TOKEN: $HUGGINGFACE_TOKEN"
         echo "REPO_OWNER: $REPO_OWNER"

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Node.js Dependencies
        run: npm install  # Installs Node.js dependencies if package.json exists

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Get Commit ID
        run: |
          echo "COMMIT_ID=${{ github.sha }}" >> $GITHUB_ENV
          echo "Short Commit ID: $(echo ${{ github.sha }} | cut -c1-7)"
          echo "Hugging face token: API_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }}"

      - name: Create Virtual Environment and Install Dependencies
        run: |
          python -m venv python-repo/venv  # Create virtual environment
          source python-repo/venv/bin/activate  # Activate virtual environment
          pip install --upgrade pip
          pip install -r python-repo/requirements.txt
        shell: bash

      - name: Verify Installed Packages
        run: |
          source python-repo/venv/bin/activate
          pip list
        shell: bash

      - name: Run Clone Repository Script
        run: |
          source python-repo/venv/bin/activate
          python python-repo/app/clone_repo.py
        shell: bash

      - name: Run Analyzer Script
        run: |
          source python-repo/venv/bin/activate
          python python-repo/app/analyzer.py
        shell: bash
        


