name: Run Python Script from Another Repo

on: 
  push:
    branches:
      - main  # Runs when code is pushed to main
  workflow_dispatch:  # Allows manual execution

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Node.js Repository
        uses: actions/checkout@v3

      - name: Checkout Python Repository
        uses: actions/checkout@v3
        with:
          repository: alphyemmanuel/dependency-deprecator-analyzer  # Change this to your Python repo
          path: python-repo  # This will clone the Python repo into a folder

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Node.js Dependencies
        run: npm install  # Installs Node.js dependencies if package.json exists

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Create and Activate Virtual Environment
        run: |
          python -m venv python-repo/venv  # Create virtual environment
          source python-repo/venv/bin/activate  # Activate virtual environment
          pip install --upgrade pip
          pip install -r python-repo/requirements.txt  # Install dependencies
        shell: bash

      - name: Verify Installed Packages (Debugging Step)
        run: |
          source python-repo/venv/bin/activate  # Activate virtual environment
          pip list  # List installed packages to verify huggingface_hub is installed
        shell: bash

      - name: Run Python Script
        run: |
          source python-repo/venv/bin/activate  # Activate virtual environment
          python python-repo/app/analyzer.py
        shell: bash
